spring:
  messages:
    basename: i18n/message
    fallback-to-system-locale: false
  main:
    allow-circular-references: true

app:
  current-locale: ru
  csv-file-path:
    question: questions_${app.current-locale}.csv