spring:
  datasource:
    url: jdbc:h2:mem:workdb
    driver-class-name: org.h2.Driver
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true